import { COLORS } from './colors';
import type { Level } from './types';
const mk=(id:number,name:string,t:number,req:number,nodes:any[],edges:any[],sockets:string[],pieces:any[],hints:string[]):Level=>({id,name,timerSeconds:t,requiredActive:true,requiredColor:req as any,nodes,edges,sockets:sockets.map(nodeId=>({nodeId})),availablePieces:pieces,hints});
export const levels:Level[]=[
mk(1,'Basic Flow',50,COLORS.GREEN,[{id:'i1',type:'input',label:'In G',x:0,y:1,inputSignal:{active:true,color:COLORS.GREEN}},{id:'s1',type:'socket',label:'Socket',x:1,y:1},{id:'out',type:'output',label:'Lock',x:2,y:1}],[{from:'i1',to:'s1'},{from:'s1',to:'out'}],['s1'],['OR'],['Place OR to pass signal.']),
mk(2,'AND Gate',55,COLORS.GREEN,[{id:'a',type:'input',label:'A',x:0,y:0,inputSignal:{active:true,color:COLORS.GREEN}},{id:'b',type:'input',label:'B',x:0,y:2,inputSignal:{active:true,color:COLORS.GREEN}},{id:'s1',type:'socket',label:'Socket',x:1,y:1},{id:'out',type:'output',label:'Lock',x:2,y:1}],[{from:'a',to:'s1'},{from:'b',to:'s1'},{from:'s1',to:'out'}],['s1'],['AND','OR'],['Need both live inputs.']),
mk(3,'Color Mixer',50,COLORS.CYAN,[{id:'g',type:'input',label:'G',x:0,y:0,inputSignal:{active:true,color:COLORS.GREEN}},{id:'b',type:'input',label:'B',x:0,y:2,inputSignal:{active:true,color:COLORS.BLUE}},{id:'s1',type:'socket',label:'Socket',x:1,y:1},{id:'out',type:'output',label:'Lock',x:2,y:1}],[{from:'g',to:'s1'},{from:'b',to:'s1'},{from:'s1',to:'out'}],['s1'],['MIXER','OR'],['Mix green + blue.']),
mk(4,'Filter Red',45,COLORS.RED,[{id:'w',type:'input',label:'W',x:0,y:1,inputSignal:{active:true,color:COLORS.WHITE}},{id:'s1',type:'socket',label:'Socket',x:1,y:1},{id:'out',type:'output',label:'Lock',x:2,y:1}],[{from:'w',to:'s1'},{from:'s1',to:'out'}],['s1'],['FILTER_RED','FILTER_BLUE'],['Strip white down to red.']),
mk(5,'XOR Maze',40,COLORS.MAGENTA,[{id:'r',type:'input',label:'R',x:0,y:0,inputSignal:{active:true,color:COLORS.RED}},{id:'b',type:'input',label:'B',x:0,y:2,inputSignal:{active:true,color:COLORS.BLUE}},{id:'x1',type:'socket',label:'XOR',x:1,y:1},{id:'m1',type:'socket',label:'Mix',x:2,y:1},{id:'out',type:'output',label:'Lock',x:3,y:1}],[{from:'r',to:'x1'},{from:'b',to:'x1'},{from:'x1',to:'m1'},{from:'r',to:'m1'},{from:'b',to:'m1'},{from:'m1',to:'out'}],['x1','m1'],['XOR','OR','MIXER'],['XOR alone kills both. route one input through XOR then mix.']),
mk(6,'Time Pressure',28,COLORS.YELLOW,[{id:'r',type:'input',label:'R',x:0,y:0,inputSignal:{active:true,color:COLORS.RED}},{id:'g',type:'input',label:'G',x:0,y:2,inputSignal:{active:true,color:COLORS.GREEN}},{id:'sw',type:'switch',label:'SW',x:1,y:0,fixedPiece:'SWITCH'},{id:'m',type:'socket',label:'Mix',x:2,y:1},{id:'dec',type:'socket',label:'Decoy',x:1,y:2},{id:'out',type:'output',label:'Lock',x:3,y:1}],[{from:'r',to:'sw'},{from:'sw',to:'m'},{from:'g',to:'m'},{from:'g',to:'dec'},{from:'dec',to:'out'},{from:'m',to:'out'}],['m','dec'],['MIXER','FILTER_BLUE','OR'],['Toggle switch ON and mix red+green.'])
];
