import { useEffect, useMemo, useState } from 'react';
import { Board } from './Board';import { HeaderTimer } from './HeaderTimer';import { PieceTray } from './PieceTray';import { PotatoBomb } from './PotatoBomb';
import { colorToName } from '../game/colors';import { levels } from '../game/levels';import { simulateLevel } from '../game/logic';import { computeScore } from '../game/scoring';import type { PieceType } from '../game/types';
export function GameScreen({levelId,onDone}:{levelId:number;onDone:()=>void}){const level=levels.find(l=>l.id===levelId)!;const [time,setTime]=useState(level.timerSeconds);const [placed,setPlaced]=useState<Record<string,PieceType>>({});const [selected,setSelected]=useState<PieceType>();const [switches,setSwitches]=useState<Record<string,boolean>>({});const [pen,setPen]=useState(0);const [hints,setHints]=useState(0);const [msg,setMsg]=useState('');const [result,setResult]=useState<any>();const [won,setWon]=useState(false);
useEffect(()=>{if(won||time<=0)return;const t=setInterval(()=>setTime(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t);},[won,time]);
const applyPenalty=(s:number)=>{setTime(t=>Math.max(0,t-s));setPen(p=>p+1)};
const run=()=>{const r=simulateLevel(level,placed,switches);setResult(r);setMsg(r.reason);if(r.success){setWon(true);const key='logic-fuse-progress';const data=JSON.parse(localStorage.getItem(key)||'{"completed":[],"best":{}}');if(!data.completed.includes(level.id))data.completed.push(level.id);data.best[level.id]=Math.max(data.best[level.id]||0,computeScore(time,pen,hints));localStorage.setItem(key,JSON.stringify(data));} else {applyPenalty(3); if(r.output.active&&r.output.color!==level.requiredColor) applyPenalty(2);} };
const hint=()=>{setHints(h=>h+1);applyPenalty(5);setMsg(level.hints[hints%level.hints.length]);};
const score=useMemo(()=>computeScore(time,pen,hints),[time,pen,hints]);
if(time===0&&!won) return <div className='screen'><h2>💥 Boom! Fuse burned out.</h2><button onClick={onDone}>Back</button></div>;
if(won) return <div className='screen'><h2>✅ Puzzle Solved!</h2><p>{msg}</p><p>Score {score}</p><button onClick={onDone}>Next/Back</button></div>;
return <div className='screen'><div className='top'><h2>Logic Fuse • Stage {level.id}</h2><HeaderTimer time={time}/><PotatoBomb time={time} exploded={false}/><p>Need TRUE + {colorToName(level.requiredColor)}</p></div><Board level={level} placed={placed} selected={selected} onToggle={(id)=>setSwitches(s=>({...s,[id]:!(s[id]??true)}))} onPlace={(id)=>{if(!selected)return; if(!level.sockets.find(s=>s.nodeId===id)) return; setPlaced(p=>({...p,[id]:selected}));}} result={result}/><PieceTray pieces={level.availablePieces} selected={selected} onSelect={setSelected}/><div className='actions'><button aria-label='run' onClick={run}>RUN SIGNAL</button><button onClick={()=>{applyPenalty(result?2:1);setPlaced({});}}>UNDO -1/-2s</button><button onClick={()=>{applyPenalty(8);setPlaced({});setResult(null);}}>RESET -8s</button><button onClick={hint}>HINT -5s</button></div><p>{msg}</p><p>Penalties:{pen} Hints:{hints} Score:{score}</p></div>}
